name: "✨ Feature Request"
description: Suggest an idea for new features.
labels: enhancement

body:
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: |
        Please share your system info with us. You can run the command **benco env** and copy-paste its output below.
        请提供您的系统信息。您可以在命令行运行 **benco env** 并将其输出复制到该文本框中。
      placeholder: benco version, platform, python version, ...
    validations:
      required: true

  - type: textarea
    id: others
    attributes:
      label: Others 
      description: |
        Describe feature you want detailly here.
        详细描述你期待的新功能。
    validations:
      required: false
