CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,1)
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 0
PRINT_FREQ: 10

DATASET:
  DATASET: splicing_dataset
  NUM_CLASSES: 2
MODEL:
  NAME: network_CAT
  PRETRAINED_RGB: '/mnt/data0/bingkui/Cat-Net/hrnetv2_w48_imagenet_pretrained.pth'
  PRETRAINED_DCT: '/mnt/data0/bingkui/Cat-Net/DCT_djpeg.pth.tar'
  EXTRA:
    FINAL_CONV_KERNEL: 1
    STAGE1:
      NUM_MODULES: 1
      NUM_RANCHES: 1
      BLOCK: BOTTLENECK
      NUM_BLOCKS:
        - 4
      NUM_CHANNELS:
        - 64
      FUSE_METHOD: SUM
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
      NUM_CHANNELS:
        - 48
        - 96
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
        - 4
      NUM_CHANNELS:
        - 48
        - 96
        - 192
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
        - 4
        - 4
      NUM_CHANNELS:
        - 48
        - 96
        - 192
        - 384
      FUSE_METHOD: SUM
    DC_STAGE3:
      NUM_MODULES: 3  # 4
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
      NUM_CHANNELS:
        - 96
        - 192
      FUSE_METHOD: SUM
    DC_STAGE4:
      NUM_MODULES: 2  # 3
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
        - 4
      NUM_CHANNELS:
        - 96
        - 192
        - 384
      FUSE_METHOD: SUM
    STAGE5:
      NUM_MODULES: 1
      NUM_BRANCHES: 4  # concat resolution-wise
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
        - 4
        - 4
      NUM_CHANNELS:
        - 24
        - 48
        - 96
        - 192
      FUSE_METHOD: SUM
LOSS:
  USE_OHEM: false
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
TRAIN:
  IMAGE_SIZE:
  - 512
  - 512
  BASE_SIZE: 512
  BATCH_SIZE_PER_GPU: 2
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 200
  RESUME: true
  OPTIMIZER: sgd
  LR: 0.005
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  DOWNSAMPLERATE: 1
  IGNORE_LABEL: -1
  SCALE_FACTOR: 11
TEST:
  IMAGE_SIZE:
  - 512
  - 512
  BASE_SIZE: 512
  BATCH_SIZE_PER_GPU: 2
  NUM_SAMPLES: 2000
  FLIP_TEST: false
  MULTI_SCALE: false
